---
version: '3.7'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_RELEASE}-${ELASTIC_ARCH_TYPE}
    container_name: es01
    ports: 
      - '9200:9200'
      - '9300:9300'
    environment:
      - cluster.name=es-cluster01
      - node.name=es01
      - http.port=9200
      - transport.port=9300
      - cluster.initial_master_nodes=es01
      - discovery.seed_hosts=es01:9300
      - node.master=true
      - node.voting_only=false
      - node.data=true
      - node.ingest=true
      - node.ml=false
      - node.attr.data_node=hot
      - node.attr.rack=eu-central-1a
      - xpack.ml.enabled=false
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
      - cluster.remote.connect=false
      - path.repo=/usr/share/elasticsearch/backup
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
    volumes:
      - ~/miniobs/miniobs-205/:/usr/share/elasticsearch/backup
      - ./resources/es01/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore
      - data01:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks: 
      - 'elastic'
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure

  kb01:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_RELEASE}
    container_name: kb01
    environment:
      - SERVER_NAME=kb01
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5601
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_USERNAME=${ELASTIC_USER}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - XPACK_APM_SERVICEMAPENABLED=TRUE
    ports: 
      - '5601:5601'
    networks: 
      - 'elastic'
    depends_on: ['es01']
    healthcheck:
      test: curl -s http://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure
  
  ls01:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_RELEASE}
    container_name: ls01
    environment:
      - 'ELASTIC_USER=${ELASTIC_USER}'
      - 'ELASTIC_PASSWORD=${ELASTIC_PASSWORD}'
      - PIPELINE_WORKERS="2"
      - XPACK_MONITORING_ENABLED="true"
      - XPACK_MONITORING_ELASTICSEARCH_USERNAME=${ELASTIC_USER}
      - XPACK_MONITORING_ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      - XPACK_MONITORING_ELASTICSEARCH_HOSTS=http://es01:9200
    volumes:
      - './resources/ls01/pipeline.yml:/usr/share/logstash/config/pipeline.yml'
      - './resources/ls01/pipeline:/usr/share/logstash/pipeline'
    ports: 
      - '9600:9600'
      - '5044:5044'
      - '5817:5817'
    networks: 
      - 'elastic'
    depends_on: 
      - 'es01'
    healthcheck:
      test: curl -s http://localhost:9600 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure

  mb01:
    image: docker.elastic.co/beats/metricbeat:${ELASTIC_RELEASE}
    user: root
    container_name: mb01
    environment:
      - 'ELASTIC_USER=${ELASTIC_USER}'
      - 'ELASTIC_PASSWORD=${ELASTIC_PASSWORD}'
    volumes:
      - ./resources/mb01/scripts:/mnt/scripts:ro
      - ./resources/mb01/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
    command: sh -c '/mnt/scripts/wait.sh $DEBUG_WAIT_FOR http://elastic:changeme@kb01:5601/api/status && metricbeat -e --strict.perms=false -e -system.hostfs=/hostfs -e '
    networks: 
      - 'elastic'
    privileged: true
    depends_on: 
      - 'es01'
      - 'kb01'
    restart: on-failure

networks:
  elastic:
    driver: bridge

volumes:
  data01:
