# For more information on multiple pipelines, see the documentation:
#   https://www.elastic.co/guide/en/logstash/current/multiple-pipelines.html

- pipeline.id: ls01-main
  path.config: "/usr/share/logstash/pipeline"
