filebeat.inputs:
- type: log
  enabled: true
  paths: 
    - ${path.config}/prospectors.d/*.yml

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
  - add_cloud_metadata:

keystore.path: "/usr/share/filebeat/data/beats.keystore"

output.elasticsearch:
  username: elastic
  password: "${ELASTIC_PASSWORD}"
  hosts: ["elasticsearch:9200"]
  protocol: https
  # Read PW from auditbeat.keystore
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]

setup.kibana:
  username: elastic
  password: "${ELASTIC_PASSWORD}"
  protocol: http
  host: "http://kibana:5601"
  ssl.enabled: false
  ssl.certificate_authorities: ["/usr/share/filebeat/certs/ca/ca.crt"]

xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch:
