---
version: '3.7'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_RELEASE}-${ELASTIC_ARCH_TYPE}
    container_name: elasticsearch
    ports: 
      - '9200:9200'
      - '9300:9300'
    environment:
      - cluster.name=es-cluster01
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - node.master=true
      - node.voting_only=false
      - node.data=true
      - node.ingest=true
      - node.ml=false
      - node.attr.data_node=hot
      - xpack.ml.enabled=false
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/es01/es01.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/es01/es01.key
      - cluster.remote.connect=false
      - path.repo=/usr/share/elasticsearch/backup
      - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
    volumes:
      - ~/miniobs/miniobs-115/:/usr/share/elasticsearch/backup
      - ./resources/es01/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore
      - data01:/usr/share/elasticsearch/data
      - certs:$CERTS_DIR
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks: 
      - 'elastic'
    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  kb01:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_RELEASE}
    container_name: kibana
    environment:
      - 'ELASTIC_USER=${ELASTIC_USER}'
      - 'ELASTIC_PASSWORD=${ELASTIC_PASSWORD}'
      - 'CERTS_DIR=${CERTS_DIR}'
    volumes:
      - './resources/kb01/kibana.yml:/usr/share/kibana/config/kibana.yml'
      - certs:$CERTS_DIR
    ports: 
      - '5601:5601'
    networks: 
      - elastic
    depends_on: 
      - es01
    healthcheck:
      test: curl -s https://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  kl01:
    image: schneidermatic/${APP_NAME}:${APP_RELEASE}
    container_name: "korrelator"
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ID=dd1c686f-cdf5-49b1-adee-89cc645f907f
      - APP_IMAGE=schneidermatic/${APP_NAME}:${APP_RELEASE}
      - APP_DESCRIPTION="Rule based event correlation service for Elasticsearch."
      - APP_RELEASE=${APP_RELEASE}
      - APP_IPADDRESS=0.0.0.0
      - APP_PORT=8000
      - APP_CONFIG_NAME=production
      - APP_ADMIN_USER=admin
      - APP_ADMIN_PASSWORD=changeme
      - APP_THREAD_NUMB=1
      - APP_SLEEP_TIME=1
      - APP_BOOTSTRAP_RETRY_INTERVAL=1
      - APP_BOOTSTRAP_RETRY_MAX=300
      - APP_FLASK_LOGGER=False
      - APP_LOG_DIR=./
      - APP_LOG_TYPE=stream
      - APP_LOG_LEVEL=DEBUG
      - APP_MAIN_LOG_NAME=app.log
      - APP_WWW_LOG_NAME=www.log
      - APP_LOG_MAX_BYTES=100_000_000
      - APP_LOG_COPIES=5
      - APP_ES_HOST=es01
      - APP_ES_PORT=9200
      - APP_ES_USER=elastic
      - APP_ES_PASSWORD=changeme
      - APP_ES_USE_SSL=True
      - APP_ES_VERIFY_CERTS=False
      - APP_ES_CA_CERTS=/korrelator/ssl/es.pem
      - APP_ES_TEMPLATE_FOLDER=/korrelator/app/templates
      - APP_ES_INDEX_STAGE_00=event
      - APP_ES_INDEX_STAGE_01=alert
      - APP_ES_INDEX_STAGE_02=incident
    restart: always
    volumes:
      - ./resources/kl01/ssl/:/korrelator/ssl
    ports: 
      - '8000:8000'
    networks:    
      - elastic
    depends_on: 
      - es01
    healthcheck:
      test: curl -s http://localhost:8000/api/v1/ >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  elastic:
    driver: bridge

volumes:
  data01:
  certs:
