---
version: '3.6'
services:
  # The environment variable "ELASTIC_RELEASE" is used throughout this file to
  # specify the version of the images to run. The default is set in the
  # '.env' file in this folder. It can be overridden with any normal
  # technique for setting environment variables, for example:
  #
  #   ELASTIC_RELEASE=7.0.0 docker-compose up
  #
  # REF: https://docs.docker.com/compose/compose-file/#variable-substitution
  #
  # Also be sure to set the ELASTIC_VERSION variable. For released versions,
  # ${ELASTIC_RELEASE} and ${ELASTIC_VERSION} will be identical, but for pre-release
  # versions, ${ELASTIC_RELEASE} might contain an extra build identifier, like
  # "6.0.0-beta1-3eab5b40", so a full invocation might look like:
  #
  #   ELASTIC_VERSION=6.0.0-beta1 ELASTIC_RELEASE=6.0.0-beta1-3eab5b40 docker-compose up
  #
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_RELEASE}-${ELASTIC_ARCH_TYPE}
    container_name: elasticsearch
    #cap_add: ['AUDIT_CONTROL', 'AUDIT_READ']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    volumes:
      - 'certs:/usr/share/elasticsearch/config/certificates/certs'
      - 'ca:/usr/share/elasticsearch/config/certificates/certs/ca'
      - 'es_config:/usr/share/elasticsearch/config'
      - 'ls_config:/logstash'
      - 'kb_config:/kibana'
      - 'es_data:/usr/share/elasticsearch/data'
      - './scripts/setup-users.sh:/usr/local/bin/setup-users.sh:ro'
      - './scripts/setup-elasticsearch.sh:/usr/local/bin/setup-elasticsearch.sh:ro'
      - './resources/elasticsearch/instances.yml:/usr/share/elasticsearch/config/certificates/certs/instances.yml'
      - './resources/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml'
    ports: 
      - '9200:9200'
      - '9300:9300'
    environment:
      - node.name=es01
      # - discovery.type=single-node
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=es-cluster01
      # - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
    networks: ['stack']
    healthcheck:
      test: curl --cacert /usr/share/elasticsearch/config/certificates/certs/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_RELEASE}
    container_name: kibana
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    volumes:
      - 'certs:/usr/share/kibana/config/certificates/certs'
      - 'ca:/usr/share/kibana/config/certificates/certs/ca'
      - 'kb_config:/usr/share/kibana/config'
      - 'kb_data:/usr/share/kibana/data/'
      - './resources/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml'
      - './scripts/setup-kibana.sh:/usr/local/bin/setup-kibana.sh:ro'
    ports: ['5601:5601']
    networks: ['stack']
    depends_on: ['elasticsearch']
    healthcheck:
      test: curl --cacert /usr/share/kibana/config/certs/ssl/ca/ca.crt -s https://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  logstash:
    image: docker.elastic.co/logstash/logstash:${ELASTIC_RELEASE}
    #image: schneidermatic/logstash:${ELASTIC_RELEASE}
    container_name: logstash
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    volumes:
      - 'certs:/usr/share/logstash/config/certificates/certs'
      - 'ca:/usr/share/logstash/config/certificates/certs/ca'
      - 'ls_config:/usr/share/logstash/config'
      - './resources/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml'
      - './resources/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf'
      - './scripts/setup-logstash.sh:/usr/local/bin/setup-logstash.sh:ro'
    ports: 
      - '9600:9600'
      - '5817:5817'
    networks: ['stack']
    depends_on: ['elasticsearch']
    healthcheck:
      test: bin/logstash -t
      interval: 60s
      timeout: 50s
      retries: 5

  auditbeat:
    image: docker.elastic.co/beats/auditbeat:${ELASTIC_RELEASE}
    container_name: auditbeat
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}', 'BEAT_TYPE=${BEAT_TYPE}']
    command: -e --strict.perms=false # -e flag to log to stderr and disable syslog/file output
    cap_add: ['AUDIT_CONTROL', 'AUDIT_READ']
    # Auditbeat must run in the main process namespace.
    pid: host
    volumes:
      - 'certs:/usr/share/auditbeat/certs'
      - 'ca:/usr/share/auditbeat/certs/ca'
      - 'ab_config:/usr/share/auditbeat'    
      - './resources/auditbeat/auditbeat.yml:/usr/share/auditbeat/auditbeat.yml'
      - './scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro'
    networks: ['stack']
    depends_on: ['elasticsearch', 'kibana']
    healthcheck:
      test: auditbeat --strict.perms=false test config
      interval: 30s
      timeout: 15s
      retries: 5

  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_RELEASE}
    container_name: filebeat
    command: -e --strict.perms=false # -e flag to log to stderr and disable syslog/file output
    # If the host system has logs at "/var/log", mount them at "/mnt/log"
    # inside the container, where Filebeat can find them.
    # volumes: ['/var/log:/mnt/log:ro']
    cap_add: ['AUDIT_CONTROL', 'AUDIT_READ']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}', 'BEAT_TYPE=${BEAT_TYPE}']
    volumes:
      - 'certs:/usr/share/filebeat/certs'
      - 'ca:/usr/share/filebeat/certs/ca'
      - 'fb_config:/usr/share/filebeat'    
      - './resources/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml'
      - './scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro'
    networks: ['stack']
    depends_on: ['elasticsearch', 'kibana']
    healthcheck:
      test: filebeat test config
      interval: 30s
      timeout: 15s
      retries: 5

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:${ELASTIC_RELEASE}
    container_name: heartbeat
    command: --strict.perms=false -e  # -e flag to log to stderr and disable syslog/file output
    cap_add: ['AUDIT_CONTROL', 'AUDIT_READ']    
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}', 'BEAT_TYPE=${BEAT_TYPE}']
    volumes:
      - 'certs:/usr/share/heartbeat/certs'
      - 'ca:/usr/share/heartbeat/certs/ca'
      - 'hb_config:/usr/share/heartbeat'    
      - './resources/heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml'
      - './scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro'
    networks: ['stack']
    depends_on: ['elasticsearch', 'kibana']
    healthcheck:
      test: heartbeat test config
      interval: 30s
      timeout: 15s
      retries: 5

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${ELASTIC_RELEASE}
    container_name: metricbeat
    # The commented sections below enable Metricbeat to monitor the Docker host,
    # rather than the Metricbeat container. It's problematic with Docker for
    # Windows, however, since "/proc", "/sys" etc. don't exist on Windows.
    # The same likely applies to OSX (needs testing).
    # volumes:
    #   - /proc:/hostfs/proc:ro
    #   - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
    #   - /:/hostfs:ro
    command: --strict.perms=false -e  # -e flag to log to stderr and disable syslog/file output
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}', 'BEAT_TYPE=${BEAT_TYPE}']
    volumes:
      - 'certs:/usr/share/metricbeat/certs'
      - 'ca:/usr/share/metricbeat/certs/ca'
      - 'mb_config:/usr/share/metricbeat'    
      - './resources/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml'
      - './scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro'
    networks: ['stack']
    depends_on: ['elasticsearch', 'kibana']
    healthcheck:
      test: metricbeat test config
      interval: 30s
      timeout: 15s
      retries: 5

  packetbeat:
    image: docker.elastic.co/beats/packetbeat:${ELASTIC_RELEASE}
    container_name: packetbeat
    # Packetbeat needs some elevated privileges to capture network traffic.
    # We'll grant them with POSIX capabilities.
    cap_add: ['NET_RAW', 'NET_ADMIN']
    # Use "host mode" networking to allow Packetbeat to capture traffic from
    # the real network interface on the host, rather than being isolated to the
    # container's virtual interface.
    # network_mode: host
    # Since we did that, Packetbeat is not part of the "stack" Docker network
    # that the other containers are connected to, and thus can't resolve the
    # hostname "elasticsearch". Instead, we'll tell it to find Elasticsearch
    # on "localhost", which is the Docker host machine in this context.
    command: --strict.perms=false -e # -e flag to log to stderr and disable syslog/file output
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}', 'BEAT_TYPE=${BEAT_TYPE}']
    volumes:
      - 'certs:/usr/share/packetbeat/certs'
      - 'ca:/usr/share/packetbeat/certs/ca'
      - 'pb_config:/usr/share/packetbeat'    
      - './resources/packetbeat/packetbeat.yml:/usr/share/packetbeat/packetbeat.yml'
      - './scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro'
    networks: ['stack']
    depends_on: ['elasticsearch', 'kibana']
    healthcheck:
      test: packetbeat test config
      interval: 30s
      timeout: 15s
      retries: 5

  journalbeat:
    image: docker.elastic.co/beats/journalbeat:${ELASTIC_RELEASE}
    container_name: journalbeat
    command: -e --strict.perms=false # -e flag to log to stderr and disable syslog/file output
    cap_add: ['AUDIT_CONTROL', 'AUDIT_READ']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}', 'BEAT_TYPE=${BEAT_TYPE}']
    volumes:
      - 'certs:/usr/share/journalbeat/certs'
      - 'ca:/usr/share/journalbeat/certs/ca'
      - 'jb_config:/usr/share/journalbeat'    
      - './resources/journalbeat/journalbeat.yml:/usr/share/journalbeat/journalbeat.yml'
      - './scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro'
    networks: ['stack']
    depends_on: ['elasticsearch', 'kibana']
    healthcheck:
      test: journalbeat --strict.perms=false test config
      interval: 30s
      timeout: 15s
      retries: 5

  apm-server:
    image: docker.elastic.co/apm/apm-server:${ELASTIC_RELEASE}
    container_name: apm_server
    ports: ['8200:8200']
    command: --strict.perms=false -e  # -e flag to log to stderr and disable syslog/file output
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}', 'BEAT_TYPE=${BEAT_TYPE}']
    volumes:
      - 'certs:/usr/share/apm-server/certs'
      - 'ca:/usr/share/apm-server/certs/ca'
      - 'apm_config:/usr/share/apm-server'    
      - './resources/apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml'
      - './scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro'
    networks: ['stack']
    depends_on: ['elasticsearch', 'kibana']
    healthcheck:
      test: curl --cacert /usr/share/apm-server/config/certs/ssl/ca/ca.crt -s https://localhost:8200/healthcheck >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

networks: {stack: {}}

# use docker volume to persist ES data outside of a container.
volumes:
  certs:
  ca:
  ssl:
  es_data:
  es_config:
  kb_config:
  kb_data:
  ls_config:
  ab_config:
  fb_config:
  hb_config:
  mb_config:
  pb_config:
  jb_config:
  apm_config:
