version: "3.6"
services:
  setup:
    build: .
    working_dir: "${PWD}"
    cap_add: ['SYS_ADMIN']
    environment:
      - "PWD=${PWD}"
      - "ELASTIC_PASSWORD"
      - "ELASTIC_RELEASE"
      - "ELASTIC_VERSION"
      - "COMPOSE_PROJECT_NAME=${PROJECT_NAME}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PWD}:${PWD}"
    entrypoint: ["/bin/bash", "-c"]
    command: ["./scripts/setup.sh"]