---
version: '3.7'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_RELEASE}-${ELASTIC_ARCH_TYPE}
    container_name: elasticsearch
    ports: 
      - '9200:9200'
      - '9300:9300'
    environment:
      - cluster.name=es-cluster01
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - node.master=true
      - node.voting_only=false
      - node.data=true
      - node.ingest=true
      - node.ml=false
      - node.attr.data_node=hot
      - xpack.ml.enabled=false
      - xpack.license.self_generated.type=trial
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/es01/es01.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/es01/es01.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/es01/es01.key
      - cluster.remote.connect=false
      - path.repo=/usr/share/elasticsearch/backup
      - "ES_JAVA_OPTS=-Xmx1g -Xms1g"
    volumes:
      - ~/miniobs/miniobs-015/:/usr/share/elasticsearch/backup
      - ./resources/es01/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore
      - data01:/usr/share/elasticsearch/data
      - certs:$CERTS_DIR
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks: 
      - 'elastic'
    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  kb01:
    image: docker.elastic.co/kibana/kibana:${ELASTIC_RELEASE}
    container_name: kibana
    environment:
      - 'ELASTIC_USER=${ELASTIC_USER}'
      - 'ELASTIC_PASSWORD=${ELASTIC_PASSWORD}'
      - 'CERTS_DIR=${CERTS_DIR}'
    volumes:
      - './resources/kb01/kibana.yml:/usr/share/kibana/config/kibana.yml'
      - certs:$CERTS_DIR
    ports: 
      - '5601:5601'
    networks: 
      - elastic
    depends_on: 
      - es01
    healthcheck:
      test: curl -s https://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  elastic:
    driver: bridge

volumes:
  data01:
  certs:
